/* Process model C form file: wpan_sink_process.pr.c */
/* Portions of this file copyright 1986-2009 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from wpan_sink_process.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char wpan_sink_process_pr_c [] = "MIL_3_Tfile_Hdr_ 150A 30A op_runsim_dev 7 4B067786 4B067786 1 nb-pju jurcikp 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 21b7 3                                                                                                                                                                                                                                                                                                                                                                                                     ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

/* Include files		*/
#include "headers\wpan_params.h"

/* Function prototypes */
static void wpan_parse_incoming_packet (void);

/* Global variables	*/
extern double PPDU_sent_bits;	// Total number of bits (data and command PPDU) dispatched to the network [kbits]


/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	Stathandle	             		bits_rcvd_stathandle                            ;	/* Traffic Received (bits) */
	Stathandle	             		bitssec_rcvd_stathandle                         ;	/* Traffic Received (bits/sec) */
	Stathandle	             		pkts_rcvd_stathandle                            ;	/* Traffic Received (packets) */
	Stathandle	             		pktssec_rcvd_stathandle                         ;	/* Traffic Received (packets/sec) */
	Stathandle	             		e2e_delay_frame_stathandleG                     ;	/* End-to-End Delay for Data and Command Frames (seconds) */
	Stathandle	             		e2e_delay_frame_stathandle                      ;	/* End-to-End Delay for Data and Command Frames (seconds) */
	} wpan_sink_process_state;

#define bits_rcvd_stathandle    		op_sv_ptr->bits_rcvd_stathandle
#define bitssec_rcvd_stathandle 		op_sv_ptr->bitssec_rcvd_stathandle
#define pkts_rcvd_stathandle    		op_sv_ptr->pkts_rcvd_stathandle
#define pktssec_rcvd_stathandle 		op_sv_ptr->pktssec_rcvd_stathandle
#define e2e_delay_frame_stathandleG		op_sv_ptr->e2e_delay_frame_stathandleG
#define e2e_delay_frame_stathandle		op_sv_ptr->e2e_delay_frame_stathandle

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	wpan_sink_process_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((wpan_sink_process_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ + 2};
#endif

/********************************************************************************* 
				IEEE 802.15.4/ZigBee OPNET Simulation Model
**********************************************************************************

Author: Petr Jurcik <petr@isep.ipp.pt> <jurcikp@control.felk.cvut.cz>
Author: Anis Koubaa <aska@isep.ipp.pt>

Organization:
	IPP-HURRAY Research Group
	CISTER/ISEP
	Polytechnic Institute of Porto, Portugal

Organization:
	Department of Control Engineering
	Faculty of Electrical Engineering
	Czech Technical University in Prague, Czech Republic
 
Copyright (c) 2007 - 2009 

This file is part of IEEE 802.15.4/ZigBee OPNET Simulation Model for OPNET Modeler. IEEE 802.15.4/ZigBee OPNET Simulation Model can be used, copied and modified under the next licenses:
 
 - GPL - GNU General Public License
 
Code can be modified and re-distributed under any combination of the above listed licenses. If a contributor does not agree with some of the licenses, he/she can delete appropriate line. If you delete all lines, you are not allowed to distribute source code and/or binaries utilizing code.


**********************************************************************************
                           GNU General Public License  

IEEE 802.15.4/ZigBee OPNET Simulation Model is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later version.
 
IEEE 802.15.4/ZigBee OPNET Simulation Model is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with IEEE 802.15.4/ZigBee OPNET Simulation Model; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 

*********************************************************************************/

/*--------------------------------------------------------------------------------
 * Function:	wpan_parse_incoming_packet
 *
 * Description:	Receive a frame MPDU from MAC layer (wpan_mac) and update statistics.
 *
 * No parameters
 *--------------------------------------------------------------------------------*/

static void wpan_parse_incoming_packet () {
	
	Packet* frame_MPDU;
	double	frame_MPDU_size;
	double	e2e_delay; // end-to-end delay

	/* Stack tracing enrty point */
	FIN(wpan_parse_incoming_packet);

	/* Obtain the incoming packet.	*/
	frame_MPDU = op_pk_get (op_intrpt_strm ());
	
	/* Caclulate metrics to be updated.		*/
	frame_MPDU_size = (double) op_pk_total_size_get (frame_MPDU);
	e2e_delay = op_sim_time () - op_pk_stamp_time_get (frame_MPDU);
	
	op_stat_write (e2e_delay_frame_stathandleG, e2e_delay);	
	op_stat_write (e2e_delay_frame_stathandle, e2e_delay);

	
	/* Update local statistics.				*/
	op_stat_write (bits_rcvd_stathandle, 		frame_MPDU_size);
	op_stat_write (pkts_rcvd_stathandle, 		1.0);
	op_stat_write (bitssec_rcvd_stathandle, 	frame_MPDU_size);
	op_stat_write (bitssec_rcvd_stathandle, 	0.0);
	op_stat_write (pktssec_rcvd_stathandle, 	1.0);
	op_stat_write (pktssec_rcvd_stathandle, 	0.0);	
	
	/* update global variable */
	PPDU_sent_bits = PPDU_sent_bits + ((double)(op_pk_total_size_get(frame_MPDU)+PHY_HEADER_SIZE)/1000.0); // in kbits
	
	
	/* Destroy the received packet.	*/
	op_pk_destroy (frame_MPDU);
	
	/* Stack tracing exit point */
	FOUT;
}

/* End of Function Block */

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void wpan_sink_process (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_wpan_sink_process_init (int * init_block_ptr);
	void _op_wpan_sink_process_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_wpan_sink_process_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_wpan_sink_process_alloc (VosT_Obtype, int);
	void _op_wpan_sink_process_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
wpan_sink_process (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (wpan_sink_process ());

		{


		FSM_ENTER_NO_VARS ("wpan_sink_process")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (init) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "init", "wpan_sink_process [init enter execs]")
				FSM_PROFILE_SECTION_IN ("wpan_sink_process [init enter execs]", state0_enter_exec)
				{
				/* Initilaize the statistic handles to keep	track of traffic sinked by this process. */
				bits_rcvd_stathandle 		= op_stat_reg ("Traffic Sink.Traffic Received (bits)",			OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				bitssec_rcvd_stathandle 	= op_stat_reg ("Traffic Sink.Traffic Received (bits/sec)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				pkts_rcvd_stathandle 		= op_stat_reg ("Traffic Sink.Traffic Received (packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				pktssec_rcvd_stathandle 	= op_stat_reg ("Traffic Sink.Traffic Received (packets/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				
				e2e_delay_frame_stathandle	= op_stat_reg ("Traffic Sink.End-to-End Delay for Data and Command Frames (seconds)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				e2e_delay_frame_stathandleG	= op_stat_reg ("Traffic Sink.End-to-End Delay for Data and Command Frames (seconds)",		OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (init) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "init", "wpan_sink_process [init exit execs]")


			/** state (init) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "init", "idle", "tr_3", "wpan_sink_process [init -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (idle) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "idle", state1_enter_exec, "wpan_sink_process [idle enter execs]")
				FSM_PROFILE_SECTION_IN ("wpan_sink_process [idle enter execs]", state1_enter_exec)
				{
				switch (op_intrpt_type()) {
					case OPC_INTRPT_STRM : 
						{
							wpan_parse_incoming_packet ();
							break;
						};
				
					default :
						{
						};
				}
				}
				FSM_PROFILE_SECTION_OUT (state1_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"wpan_sink_process")


			/** state (idle) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "idle", "wpan_sink_process [idle exit execs]")


			/** state (idle) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "idle", "idle", "tr_4", "wpan_sink_process [idle -> idle : default / ]")
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"wpan_sink_process")
		}
	}




void
_op_wpan_sink_process_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_wpan_sink_process_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_wpan_sink_process_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_wpan_sink_process_svar function. */
#undef bits_rcvd_stathandle
#undef bitssec_rcvd_stathandle
#undef pkts_rcvd_stathandle
#undef pktssec_rcvd_stathandle
#undef e2e_delay_frame_stathandleG
#undef e2e_delay_frame_stathandle

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_wpan_sink_process_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_wpan_sink_process_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (wpan_sink_process)",
		sizeof (wpan_sink_process_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_wpan_sink_process_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	wpan_sink_process_state * ptr;
	FIN_MT (_op_wpan_sink_process_alloc (obtype))

	ptr = (wpan_sink_process_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "wpan_sink_process [init enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_wpan_sink_process_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	wpan_sink_process_state		*prs_ptr;

	FIN_MT (_op_wpan_sink_process_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (wpan_sink_process_state *)gen_ptr;

	if (strcmp ("bits_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bits_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("bitssec_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bitssec_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("pkts_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("pktssec_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pktssec_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("e2e_delay_frame_stathandleG" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->e2e_delay_frame_stathandleG);
		FOUT
		}
	if (strcmp ("e2e_delay_frame_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->e2e_delay_frame_stathandle);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

